Задание 2
htmlacademy-javascript/1336325-keksobooking-22 pull request #2
Opened 2021-01-30 12:51 UTC by YurchenkoValentin

Добавляет функции для получения случайного числа из диапозона.

2021-01-31 05:30 UTC, markovalenko requested changes

2021-01-31 05:30 UTC, markovalenko commented on js/main.js
> +/*jslint node: true */
Не знаю, зачем это строка, пожалуйста - расскажи.

2021-01-31 05:30 UTC, markovalenko commented on js/main.js
> +/*jslint node: true */
Согласно критерию Б16, необходимо добавлять 'use strict'; на первую строку каждого файла. [(читать про строгий режим)](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Strict_mode)

2021-01-31 05:30 UTC, markovalenko commented on js/main.js
> +const getRandomNumber = function (min, max) {
```suggestion
const getRandomNumber = (min, max) => {
```

2021-01-31 05:30 UTC, markovalenko commented on js/main.js
> +const getRandomNumber = function (min, max) {
Предлагаю использовать стрелочные функции. [(читать про стрелочные функции)](https://habr.com/ru/post/268795/)

2021-01-31 05:30 UTC, markovalenko commented on js/main.js
> +let getCoordinates = function (min, max, numberOfSymbols) {
```suggestion
let getCoordinates = (min, max, numberOfSymbols) => {
```

2021-01-31 05:30 UTC, markovalenko commented on js/main.js
> +let getCoordinates = function (min, max, numberOfSymbols) {
Почему ты использовал `let` для определения переменной? Если ты не планируешь к этой переменной привязывать "другую память", нужно использовать ключевое слово `const`.

2021-01-31 09:23 UTC, YurchenkoValentin commented on js/main.js
> +const getRandomNumber = function (min, max) {
Хорошо

2021-01-31 09:25 UTC, YurchenkoValentin commented on js/main.js
> +let getCoordinates = function (min, max, numberOfSymbols) {
**Будет использоваться для генерации временных географических координат в следующем задании.**

Я решил, если координаты временные, то это не const

2021-01-31 13:16 UTC, YurchenkoValentin commented on js/main.js
> +/*jslint node: true */
Вызовы функции обернуты в скобки, потому что проверял через console.log и забыл удалить

2021-02-01 05:35 UTC, markovalenko commented on js/main.js
> +let getCoordinates = function (min, max, numberOfSymbols) {
Не уверен, что это так, скорее всего будет похожее на 
```let coordinates = getCoordinates(0,20,2);```
Т.е. будут создаваться координаты опираясь на твою функцию, вряд-ли придется переопределять перемененную getCoordinates. Лучше ее оставить за функцией.

2021-02-01 09:45 UTC, YurchenkoValentin commented on js/main.js
> +let getCoordinates = function (min, max, numberOfSymbols) {
Хорошо. Изменил на const

2021-02-01 10:42 UTC, merged